CREATE DATABASE IF NOT EXISTS user_auth;
USE user_auth;
CREATE TABLE users(
id INT PRIMARY KEY AUTO_INCREMENT,
uname VARCHAR(50) NOT NULL,
uemail VARCHAR(50) UNIQUE NOT NULL,
upass VARCHAR(50) NOT NULL
);

SELECT * FROM users;